# Generated by Django 3.0.3 on 2020-08-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_mobile', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True, null=True)),
                ('screenshot_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('screenshot_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('screenshot_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('screenshot_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('screenshot_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('screenshot_6', models.ImageField(blank=True, null=True, upload_to='')),
                ('screenshot_7', models.ImageField(blank=True, null=True, upload_to='')),
                ('screenshot_8', models.ImageField(blank=True, null=True, upload_to='')),
                ('screenshot_9', models.ImageField(blank=True, null=True, upload_to='')),
                ('screenshot_10', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(blank=True, default='screenshot', max_length=255, null=True)),
                ('features_1', models.CharField(blank=True, max_length=50, null=True)),
                ('features_2', models.CharField(blank=True, max_length=50, null=True)),
                ('features_3', models.CharField(blank=True, max_length=50, null=True)),
                ('features_4', models.CharField(blank=True, max_length=50, null=True)),
                ('features_5', models.CharField(blank=True, max_length=50, null=True)),
                ('features_6', models.CharField(blank=True, max_length=50, null=True)),
                ('features_7', models.CharField(blank=True, max_length=50, null=True)),
                ('features_8', models.CharField(blank=True, max_length=50, null=True)),
                ('features_9', models.CharField(blank=True, max_length=50, null=True)),
                ('features_10', models.CharField(blank=True, max_length=50, null=True)),
                ('features_11', models.CharField(blank=True, max_length=50, null=True)),
                ('features_12', models.CharField(blank=True, max_length=50, null=True)),
                ('features_13', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies_1', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies_2', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies_3', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies_4', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies_5', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies_6', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies_7', models.CharField(blank=True, max_length=50, null=True)),
                ('technologies_8', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
