# Generated by Django 3.0.3 on 2020-08-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200831_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_1',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_10',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_2',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_3',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_4',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_5',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_6',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_7',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_8',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_9',
            field=models.CharField(blank=True, default='screenshot', max_length=255, null=True),
        ),
    ]
